spring:
  application:
    name: urlshortener
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_CONNECTION_STRING:jdbc:postgresql://localhost:5432/urlshortener}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
springdoc:
  swagger-ui:
    enabled: true
    path: /docs.html
  api-docs:
    enabled: true
    path: /docs
    version: openapi_3_1
  writer-with-order-by-keys: true